name: app
description: The mobile app for Socialko, an open source social media app. 

publish_to: 'none'

version: 1.0.0-ahsoka

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^3.0.1
  flutter_iconly: ^1.0.2
  flutter_markdown: ^0.6.14
  flutter_expandable_fab: ^1.7.0
  expandable: ^5.0.1

  # Image Manipulation
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1

  # JSON Management
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
    
  # Storage
  flutter_secure_storage: ^7.0.1
  
  # Utils
  http: ^0.13.5
  url_launcher: ^6.1.9

  # State Management
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^1.1.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"